### ISSUE TITLE
Network overview: Combine 127.0.0.1 and ::1

### ISSUE THREAD

**Issue by cgzones** [pi-hole/web#1492]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---

**Expected behavior:**

`Combined entry for 127.0.0.1 and ::1`

**Actual behavior:**

`Separate entries for 127.0.0.1 and ::1`

If all local DNS requests are running over IPv6 the 127.0.0.1 entry becomes red indicating a disabled client.
Because the hardware address is `N/A`, the entries do not get automatically combined.

**Comment by dschaper** [comment]
They really are separate addresses for accounting and overview purposes. 

But a Feature Request is still applicable.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
