### ISSUE TITLE
table id=groupsTable - Invalid JSON response

### ISSUE THREAD

**Issue by tjvanpat** [pi-hole/web#1670]
### Versions
```
  Pi-hole version is v5.2.2 (Latest: v5.2.2)
  AdminLTE version is v5.2.2 (Latest: v5.2.2)
  FTL version is v5.3.4 (Latest: v5.3.4)
```

### Platform
```
root@DietPi:~# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
root@DietPi:~# uname -r
5.4.79-v7+
```

- Platform:  Raspberry Pi 3

### Expected behavior

I clicked:
`Group Management -> Groups`

I expected this to work correctly.

### Actual behavior / bug

Instead, I received the notification dialog box containing:

> DataTables warning: table id=groupsTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

### Steps to reproduce

1. Go to `Group Management -> Groups`

## Debug Token

- URL:  https://tricorder.pi-hole.net/742xgs99j5 

### Screenshots

![piholeError](https://user-images.githubusercontent.com/4099552/103177070-5e264e00-4834-11eb-82d3-735e66ebfc9c.png)

**Comment by PromoFaux** [comment]
Please open up the chrome developer console (F12) and navigate to the network tab.. then reload the `groups.php` page. That should show the response being received, like so:

![image](https://user-images.githubusercontent.com/1998970/103177502-03601700-4873-11eb-9142-b44652b8cfc6.png)

**Comment by dschaper** [comment]
Check your `/var/log/lighttpd/error.log` and note the CORS errors. The changes you made to `/etc/lighttpd/lighttpd.conf` have affected the installation.

**Comment by tjvanpat** [comment]
I'm pretty sure I haven't touched `/etc/lighttpd/lighttpd.conf`.   It's possible the diet-pi config did something though.

Based on the CORS errors, I updated `/var/www/html/admin/scripts/pi-hole/php/auth.php` to add the domain name to `$AUTHORIZED_HOSTNAMES`, which seems to have solved the problem.   I'm not sure how long that fix will last or if the next update will wipe it out though.

Trying to fix this via updates to `/etc/lighttpd/external.conf` didn't make any difference.

Looks good for now.   Thanks much.

**Comment by PromoFaux** [comment]
> if the next update will wipe it out though.

It will :)

**Comment by tjvanpat** [comment]
What's the correct way to fix this?

**Comment by dschaper** [comment]
>  It's possible the diet-pi config did something though.

@michaing

**Comment by MichaIng** [comment]
@tjvanpat 
Did you install Pi-hole via `dietpi-software` or did you call the installer manually? In the second case, we'd not touch the `lighttpd.conf`, in the first case, `/etc/lighttpd/external.conf` would not work expectedly (it's a Pi-hole-only implementation) but instead you could create a configuration e.g. as `/etc/lighttpd/conf-available/99-my.conf`, then run `lighty-enable-mod my; systemctl reload lighttpd`.

I just tried to replicate the issue on a Pi-hole install via `dietpi-software` (with Lighttpd) but it works fine here. Since Lighttpd should by default set the referrer correctly to pass CORS check (`$_SERVER[]` array), what exactly did it set that failed the test?

**Comment by tjvanpat** [comment]
@MichaIng 

> Did you install Pi-hole via dietpi-software or did you call the installer manually?

via dietpi-software.

To be totally clear in case anyone else comes across this in the future (myself included), I added the following to `99-my.conf` (replacing `my` with my domain):
```
setenv.add-environment = ( "VIRTUAL_HOST" => "pihole.my.net" )
```

This seems to work with the changes to `/var/www/html/admin/scripts/pi-hole/php/auth.php` removed.   Thanks for everyone's help.

**Comment by MichaIng** [comment]
Do you have any kind of proxy or redirect/rewrite in front of that webserver? Would be interesting if the issue is the same with the Pi-hole Lighttpd config: https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian

Like ours, it does not set the `server.name` setting, which means that in PHP the `$_SERVER['SERVER_NAME']` variable is set to `$_SERVER['HTTP_HOST']` automatically, which is set to the "host" header from the request, being the hostname/IP that was entered in the browser/client, when not manipulated. Aside of the entered local IP addresses + "localhost" and "pi.hole", that server name is part of the accepted host names array. Now what the CORS check does is checking `$_SERVER['HTTP_HOST']` against the array, which hence will always match `$_SERVER['SERVER_NAME']` as long as there is nothing else (aside of Lighttpd) that manipulates/sets either the one or the other.

Not sure how the `VIRTUAL_HOST` variable play a role here, probably it is used as a more trustable fallback for SERVER_NAME (as set by the server) than HTTP_HOST.
________
Another thing I remember is that the referrer needs to set, i.e. **"Referrer-Policy"** HEADER must not be set to **"no-referrer"**, else the SERVER_NAME variable is empty, AFAIR. Since we had a user applying strict security headers once, our Apache2 config now assures that this is next secure working "same-origin": https://github.com/MichaIng/DietPi/blob/master/.conf/dps_93/apache.pihole.conf#L8-L9
Not sure why I didn't add this as failsafe step to Lighttpd and Nginx configs as well 🤔.
________
I'm just setting up a test Pi-hole official installer instance to verify it behaves as I expect, but doesn't that mean that with the current official Lighttpd config (no `server.name` set), the CORS check is moreless useless as it always succeeds as long as nothing "behind" Lighttpd changes either SERVER_NAME or HTTP_HOST?

**EDIT: Verified on standard Pi-hole install:**
```
2020-12-28 18:38:53 root@VM-Buster:/var/www/html# curl localhost/index.php
HTTP_HOST: localhost
SERVER_NAME: localhost
2020-12-28 18:38:54 root@VM-Buster:/var/www/html# curl 127.0.0.1/index.php
HTTP_HOST: 127.0.0.1
SERVER_NAME: 127.0.0.1
2020-12-28 18:39:01 root@VM-Buster:/var/www/html# curl -H 'host: fake' 127.0.0.1/index.php
HTTP_HOST: fake
SERVER_NAME: fake
2020-12-28 18:39:12 root@VM-Buster:/var/www/html# cat index.php
<?php
echo 'HTTP_HOST: ' . $_SERVER['HTTP_HOST'] . PHP_EOL;
echo 'SERVER_NAME: ' . $_SERVER['SERVER_NAME'] . PHP_EOL;
?>
```
Not sure how to reliably trigger a CORS test, but at least the following does not return an error response:
```
# curl -ILH 'host: fake' 127.0.0.1/admin/
HTTP/1.1 200 OK
Set-Cookie: PHPSESSID=cjrjt7tbdg9pdfj36m3sma4t2f; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-type: text/html; charset=UTF-8
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
Date: Mon, 28 Dec 2020 17:40:35 GMT
Server: lighttpd/1.4.53
```

**Comment by timvpGoogle** [comment]
Sorry for the late reply, I didn't get a chance to take a look at this yesterday.

> Do you have any kind of proxy or redirect/rewrite in front of that webserver?
Yes, I have Pi-hole behind an Nginx reverse-proxy which redirects `pihole.domain.net` to my Pi-hole IP address.   The config itself is pretty simple:

```
nginx@nginx:/etc/nginx/conf.d$ cat pihole.conf
server  {
    server_name  pihole.domain.net;

    location  / {
        proxy_buffering  off;
        proxy_pass  http://192.168.1.106;
        proxy_http_version  1.1;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  Upgrade $http_upgrade;
        proxy_set_header  Connection $http_connection;
        access_log  on;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/pihole.domain.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pihole.domain.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server  {
    if ($host = pihole.domain.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name  pihole.domain.net;
    listen 80;
    return 404; # managed by Certbot
}
```

As you can see though, I don't have the `Referrer-Policy` set to `no-referrer`.   I can try adding that too.

**Comment by tjvanpat** [comment]
Sorry for the late reply, I didn't get a chance to take a look at this yesterday.

> Do you have any kind of proxy or redirect/rewrite in front of that webserver?
Yes, I have Pi-hole behind an Nginx reverse-proxy which redirects `pihole.domain.net` to my Pi-hole IP address.   The config itself is pretty simple:

```
nginx@nginx:/etc/nginx/conf.d$ cat pihole.conf
server  {
    server_name  pihole.domain.net;

    location  / {
        proxy_buffering  off;
        proxy_pass  http://192.168.1.106;
        proxy_http_version  1.1;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  Upgrade $http_upgrade;
        proxy_set_header  Connection $http_connection;
        access_log  on;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/pihole.domain.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pihole.domain.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server  {
    if ($host = pihole.domain.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name  pihole.domain.net;
    listen 80;
    return 404; # managed by Certbot
}
```

As you can see though, I don't have the `Referrer-Policy` set to `no-referrer`.   I can try adding that too.

**Comment by MichaIng** [comment]
> Yes, I have Pi-hole behind an Nginx reverse-proxy which redirects pihole.domain.net to my Pi-hole IP address.

Ah okay, that will cause the issue. Above I mixed up the host check (which compares HTTP_HOST against SERVER_NAME) with the actual CORS check which compares HTTP_ORIGIN against SERVER_NAME. And now I understand why this fails:
- The browser adds `pihole.domain.net` to the "Origin" header (HTTP_ORIGIN in PHP).
- The Nginx proxy by default sends the proxy_pass directive host as "Host" header (HTTP_HOST in PHP), in your case `192.168.1.106`.
- Lighttpd applies the "Host" header `192.168.1.106` as server name (SERVER_NAME in PHP), since it has no explicit server name defined.
- Pi-hole now compares HTTP_ORIGIN `pihole.domain.net` with SERVER_NAME `192.168.1.106` which fails.

So you can either add `server.name = "pihole.domain.net"` to the Lighttpd configuration (setting VIRTUAL_HOST variable seems to have worked as Lighttpd seems to prioritise it as fallback compared to "Host" header, if no server name is defined) or you instruct Nginx to keep/forward the "Host" header of the initial request:
```
 proxy_set_header Host $host;
```

So in a way, CORS check works as expected as it detected a mismatch between the host the browser called and the host it was called with. But since the "Host" header can so easily be manipulated, it has limited value as long as Lighttpd is not given a fixed server name that must match the "Origin" set by the browser (or the servers local IP, "localhost" or "pi.hole"), to rule out a malicious website forwarding the requests.

> As you can see though, I don't have the Referrer-Policy set to no-referrer. I can try adding that too.

Don't do it, as that would break CORS check, as this sets the "Origin" header (`HTTP_ORIGIN`) to "null", at least with Apache2: https://github.com/MichaIng/DietPi/issues/3675

**Comment by tjvanpat** [comment]
Adding `proxy_set_header Host $host;` works when I got to `pihole.domain.net/admin` (and `pihole.domain.net/admin/groups.php`), however I get the following when just going to `pihole.domain.net`:

![pihole](https://user-images.githubusercontent.com/4099552/103325960-6edcec80-4a0b-11eb-9bf0-f135cbeb8153.png)

It seems this is expected based on this discussion:
https://discourse.pi-hole.net/t/pihole-local-blocked-because-is-not-found-on-any-blacklist/20655

Thanks again for all of the help on this.   I'm certainly far from an expert, so it's been interesting to try and follow along with everything.

**Comment by MichaIng** [comment]
> It seems this is expected based on this discussion

Yes exactly, since there is no index page file in the document root, it returns 404 and the Lighttpd config 404 handler is the blocking page (this is the way how that page can be shown for blocked content, regardless of the URL path). The information from the forum seems outdated as it is not Lighttpd which handles `pi.hole` special but the blocking page itself does some host-based redirection or shows different content based on it: https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php#L52-L86

**Comment by WebDesignerlol** [comment]
for anyone struggling with this still, this helped me avoid the table json errors as well as redirection on main page login:
this is way easier imo then the listed fixes with lttpd that would break with subsequent updates and require reconfiguring.

on reverse proxy:
change:
 `"location"  /  {"` to `"location /admin/ {"`
and add:
```
location / {
redirect 301 /admin/;
}
```

**Comment by misuchiru03** [comment]
> I'm pretty sure I haven't touched `/etc/lighttpd/lighttpd.conf`. It's possible the diet-pi config did something though.
> 
> Based on the CORS errors, I updated `/var/www/html/admin/scripts/pi-hole/php/auth.php` to add the domain name to `$AUTHORIZED_HOSTNAMES`, which seems to have solved the problem. I'm not sure how long that fix will last or if the next update will wipe it out though.
> 
> Trying to fix this via updates to `/etc/lighttpd/external.conf` didn't make any difference.
> 
> Looks good for now. Thanks much.

Before this last update to the docker pihole, the whole `external.conf` configuration was sufficient. I updated and it all broke again, though the external.conf had not changed and the problem came back.

This fix here solved it for me. Thank you very much. I'm not sure what happened between the last two versions of the docker image.

**Comment by PromoFaux** [comment]
@misuchiru03 this is a very old thread. As you are using docker you can achieve the same with the `CORS_HOSTS` or `VIRTUAL_HOST` environment variable.

See the readme of that project for more details: https://github.com/pi-hole/docker-pi-hole

> I'm not sure what happened between the last two versions of the docker image.

Things changed - that's why we publish release notes ;)  https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

**Comment by misuchiru03** [comment]
> @misuchiru03 this is a very old thread. As you are using docker you can achieve the same with the `CORS_HOSTS` or `VIRTUAL_HOST` environment variable.
> 
> See the readme of that project for more details: https://github.com/pi-hole/docker-pi-hole
> 
> > I'm not sure what happened between the last two versions of the docker image.
> 
> Things changed - that's why we publish release notes ;) https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

Yup, that makes sense. Layer 8 issue on my end. New to both pihole and docker, still getting used to running/updating them. As you mentioned: 

>Another thing to note is that if you currently have custom configurations in `external.conf`, then please move that file to `/etc/lighttpd/conf-enabled/whatevername.conf`. For upgrades, `external.conf` will still work – but future versions will likely remove the use of this file. Version 6, for example, will remove the use of lighttpd all together.

I will make note of the location of the change notes. Thanks again.

**Comment by them7d** [comment]
```
<b>Fatal error</b>:  Uncaught Error: Undefined constant &quot;SQLITE3_OPEN_READONLY&quot; in /var/www/html/admin/scripts/pi-hole/php/database.php:57
Stack trace:...

```
I have same error "table id=groupsTable - Invalid JSON response" and I checked the ajax response it shows that sqlite3 function error then I tried to install sqlite3 for my raspberry it seems fixed issue

OS: Raspberry Pi OS
server: apache2

**Comment by rdwebdesign** [comment]
Same message, but your error is unrelated.

> Error: Undefined constant &quot;SQLITE3_OPEN_READONLY&quot; in /var/www/html/admin/scripts/pi-hole/php/database.php:57

This means your PHP install doesn't have SQLITE3 modules installed (or maybe they are not correctly configured).
You need to install/configure PHP modules `pdo_sqlite` and `sqlite3`.

**Comment by MichaIng** [comment]
The PHP module is required, like `php-sqlite3` APT package, but the `sqlite3` package/command is not, since all Pi-hole scripts use the embedded `pihole-FTL sqlite3` since a while.

**Comment by rdwebdesign** [comment]
Yes. 
My comment was only about PHP modules.

To check if the modules are correctly installed and enabled, you can create a file:
```console
echo '<?php phpinfo(); ?>' > /var/www/html/admin/info.php
```
Then on the browser, access the file using http://pi.hole/admin/info.php

Both PHP modules (`sqlite3` and `pdo_sqlite`) should be enabled to use SQLITE3 functions/constants.

Example:
![image](https://github.com/pi-hole/web/assets/1385443/ad45b0ae-dc50-4d18-8872-40ba012a46f1)
![image](https://github.com/pi-hole/web/assets/1385443/ed57f91d-4476-4f1a-80d8-677a0ac3b280)
