### ISSUE TITLE
the new update has Datatables error

### ISSUE THREAD

**Issue by muhanadali100** [pi-hole/web#1745]
Pi-hole v5.2.4
Web Interface v5.4
FTL v5.7 

the new update has a datatables error

![643](https://user-images.githubusercontent.com/31727156/108562122-71273d00-7310-11eb-816e-2864c09b7bea.png)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
