### ISSUE TITLE
Website denies serving home.arpa TLD

### ISSUE THREAD

**Issue by willis936** [pi-hole/web#1753]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be _replicated_.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---

**Expected behavior:**

Access pi-hole landing website (admin link) via home.arpa TLD.  home.arpa is reserved for local DNS entries.

**Actual behavior:**
The webpage is not served citing that the name is not present in any blacklist.

**Steps to reproduce:**
1. Make a local DNS A record of the raspberry pi’s IP with a home.arpa TLD.
2. Open a browser to the raspberry pi’s home.arpa address (without “/admin”).

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

Manually added regex whitelist for home.arpa.  The error message changed to that the address was manually blacklisted.

Removing the regex whitelist and putting in a domain whitelist entry results in the page still not being served but with no error cited.

**Comment by DL6ER** [comment]
Every domain linking to the Pi-hole will show the blocking page without you navigating explicitly to `/admin`. This is expected and a necessity to have things working correctly when in `IP` blocking mode. The only special thing about `pi.hole` is that it automatically detects that you likely wanted to visit `/admin`. This automatic redirecting isn't done for *any* other domain to avoid the Pi-hole dashboard showing up in locations where ads would be loaded, otherwise.

The domain to be used for the redirection can be configured in the upcoming Pi-hole v6.0, however, with the current v5.x version such a setting is not exposed.

**Comment by willis936** [comment]
Makes sense.  Thanks.
