### ISSUE TITLE
Feature Request: Improve history search

### ISSUE THREAD

**Issue by Dubz** [pi-hole/web#1846]
Querying search for history needs to be updated. Currently I have to select how long of a timespan I may need, wait for that entire list to load (hoping it does), then utilize the search on that resulting data set to try and find what I'm looking for.

I'm basically looking for the following:
Someone triggered a domain block on an external DNS filtering service (Cloudflare Teams, OpenDNS, etc.)
That domain may be a security concern, or inappropriate (adult) for that environment

It would be nice if I cloud look up "malware.net" in the search, then pull up all the hits for that, and the requesting client for it. This way I can track down potential asset compromises or inappropriate use more easily.

**Comment by PromoFaux** [comment]
Feature requests should go to discourse.pi-hole.net (per the guidance when pressing the "New issue" button)

That said. Yes, this is less than ideal - currently the API returns _all_ results rather than just a page at a time. The upcoming (don't ask when!) v6 will feature server side pagination for the data table, which will VASTLY speed up searching/filtering on historic data

In the mean time, you can take a look at the database directly:

https://docs.pi-hole.net/database/ftl/

**Comment by Dubz** [comment]
Oh solid, that sounds great! Definitely excited for that to come.

I'll have to try and keep that in mind regarding feature requests too. Thanks!
