### ISSUE TITLE
Whitelist/Blacklist buttons in action column not always visible

### ISSUE THREAD

**Issue by Georg871** [pi-hole/web#1847]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  Debian  Raspberry Pi

- Platform:  Raspberry Pi

### Expected behavior

when using the Recent Queries the Action column sometimes is not visible

### Actual behavior / bug

when using the Recent Queries the Action column sometimes is not visible

### Steps to reproduce

1. Go to 'Query log'
2. See error (screenshot attached)

## Debug Token

- URL:  

### Screenshots
![image](https://user-images.githubusercontent.com/87386137/125495596-827d229b-ee94-4ff9-8eec-ca77bc27e1dc.png)

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Debug token?

**Comment by Georg871** [comment]
Hope this is it
Your debug token is: https://tricorder.pi-hole.net/vzbjbgy5r7

**Comment by yubiuser** [comment]
Your debug log is fine except of a single error line

`   2021-07-13 19:10:57: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 10485760 bytes) in /var/www/html/admin/api_db.php on line 437`

This usually happens if you try to get to many entries from the long term database and php memory allocation is to little.

____
Can you reproduce the error in different browsers? Do you have any browser plugins enabled that might interfere with the query log?

**Comment by Georg871** [comment]
I tried it today in Chrome ( 91.0.4472.124) and Firefox (89.0.2 (64-bit)), both being un co-operative in that the error is not showing on either. Will keep trying.
