### ISSUE TITLE
pi.hole/admin/db_queries.php doesn't show client's name but shows client IP 

### ISSUE THREAD

**Issue by stefanostatuti** [pi-hole/web#1889]
### Versions
  Pi-hole version is v5.4 (Latest: v5.4)
  AdminLTE version is v5.6 (Latest: v5.6)
  FTL version is v5.9 (Latest: v5.9)

### Platform
- OS and version:  Raspberry Pi OS
Release date: May 7th 2021
Kernel version: 5.10

### Expected behavior

pi.hole/admin/db_queries.php should be show the hostname (if configured) instead the IP (or both)

### Actual behavior / bug

pi.hole/admin/db_queries.php doesn't show client's name but shows client IP 

### Steps to reproduce

1. Go to 'pi.hole/admin/db_queries.php'

## Debug Token

- URL:  https://tricorder.pi-hole.net/oBwOtJk5/

### Screenshots

![immagine](https://user-images.githubusercontent.com/4499372/133204644-16d756a5-5019-4023-9800-979c5a59abd2.png)
my actual configuration:
![immagine](https://user-images.githubusercontent.com/4499372/133204862-29ec6531-10a3-4758-8068-16b16a63ba66.png)

**Comment by yubiuser** [comment]
I don't think IPs from the long-term database were ever associated with hostnames. There is a very practical reason not to do this: Whatever had the IP address 192.168.1.12 three months ago doesn't need to be the same one today. There might be setups where IPs are very stable, but we can not generalize this. A lot of users use DHCP servers with sequential IP assignment where devices get different IPs every day depending on who came first in the morning.

**Comment by yubiuser** [comment]
I was wrong about this. 
Pi-hole tries to get the hostnames also for the long-term database

https://github.com/pi-hole/AdminLTE/blob/50f43bde73d25211ac2c81e9092be67512611d2a/api_db.php#L22-L38

The reason it might fail is: `gethostbyaddr`resolve the hostname via the first server configures in `/etc/resolv.conf` Since we do not set 127.0.0.1 to resolv.conf anymore, the upstream server might be a public server unaware of the local DNS records.

The solution would be to use direct those queries to Pi-hole. 
As a workaround please try to add `nameserver 127.0.0.1` to your `/etc/resolv.conf`

**Comment by jgrisham** [comment]
Perhaps the previous functionality should be eventually restored if the long-term database stored MAC addresses instead of (or in addition to) IP addresses.

Granted, this would still not be perfect on routed LANs, but more complex networks are more likely to have static host IP addresses or at least deterministic DHCP servers.

(Regardless of all of that, though, if someone has hard-coded IP address/hostname assignments into the web interface, it seems a fairly safe proposition to replace them automatically when displaying the long-term log.)

**Comment by yubiuser** [comment]
This PR is the first step towards saving hostnames in the query database without blowing up the database size a lot:
https://github.com/pi-hole/FTL/pull/1255
