### ISSUE TITLE
Settings->System no longer shows IP Address

### ISSUE THREAD

**Issue by marsfan** [pi-hole/web#1927]
### Versions

- Pi-hole:  v5.5
- AdminLTE:  v5.7
- FTL:  v5.10.2

### Platform

- OS and version:  Raspbian 10 Buster

- Platform:  Raspberry Pi

### Expected behavior

Going to Settings->System on the Pi Hole Web Interface will have a field that displays the Pi Hole's current IP address and Hostname

### Actual behavior / bug

The Settings->System page no longer has fields that display the Pi Hole's IP Address, nor the hostname.

### Steps to reproduce

1. Go to the Pi Hole Web Interface

## Debug Token

- URL:  

 https://tricorder.pi-hole.net/kmFjQfxE/

### Screenshots

![image](https://user-images.githubusercontent.com/9311953/137615662-0a85af71-9bbc-49c5-b808-ffab00dadc6a.png)

**Comment by yubiuser** [comment]
This is by design. This information was not reliable as it was set only during Pi-hole installation. If your IP address changed, you needed to run `pihole -r` manually to change the displayed information. It was removed by https://github.com/pi-hole/AdminLTE/commit/cf917a6391a6a309be9dfdf87f0bde7c66d698b4

**Comment by marsfan** [comment]
@yubiuser That makes sense. Somehow I missed that when looking through the changelog.
