### ISSUE TITLE
Update failure due to PHP error

### ISSUE THREAD

**Issue by Conor0Callaghan** [pi-hole/web#2004]
### Versions

- Pi-hole:  5.6
- AdminLTE:  5.8
- FTL:   5.11

### Platform

- OS and version:  CentOS7 x64
- Platform:  VM

### Expected behavior

Upgrading pihole to work as expected. 

### Actual behavior / bug

Upgrade works, but webpage fails to display with error 500. Logs for lighthttpd show the following: 

```
2021-12-14 11:36:18: (mod_fastcgi.c.421) FastCGI-stderr: PHP Parse error:  syntax error, unexpected '.' in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 54
2021-12-14 11:36:18: (mod_fastcgi.c.421) FastCGI-stderr: PHP Parse error:  syntax error, unexpected '.' in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 54
``` 

### Steps to reproduce

Updated pihole to the latest version using the update script. Restart lighthttpd

### Additional context

Removing the ... from the line 54 in auth.php resolves the issue and webpage displays correctly. 
PHP being used is rh-php73 from centos-sclo-rh .

**Comment by DL6ER** [comment]
The `...` has been added in https://github.com/pi-hole/AdminLTE/pull/1822 The `...` operator can also be used when calling functions to unpack an array or Traversable variable or literal into the argument list:

[Example for using `...` to provide arguments](https://www.php.net/manual/en/functions.arguments.php#functions.variable-arg-list):

``` php
<?php
function add($a, $b) {
    return $a + $b;
}

echo add(...[1, 2])."\n";

$a = [1, 2];
echo add(...$a);
?>
```

The above example will output:
``` plain
3
3
```

According to [`PHP RFC: Argument Unpacking`](https://wiki.php.net/rfc/argument_unpacking) this feature is implemented since **PHP 5.6**.

The absence of this standard feature in `rh-php73` looks like a CentOS bug.

**Comment by yubiuser** [comment]
This is why Pi-hole recommends installing PHP 7 during the installation on Centos 7.
https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/automated%20install/basic-install.sh#L423-L443

**Comment by Conor0Callaghan** [comment]
> This is why Pi-hole recommends installing php 7.4 during the installation on Centos 7. https://github.com/pi-hole/pi-hole/blob/2673c2c0720fb3871a4c3cae6a3f38f9ccede24e/automated%20install/basic-install.sh#L423-L443

Thanks @yubiuser  , should this be bumped to remi-php74? ``REMI_REPO="remi-php72"``

**Comment by yubiuser** [comment]
I don't think so. PHP72 works fine right now. We don't need any functions that were introduced later. For Pi-hole v6 we try to get rid of PHP altogether. Upgrading it without need from our side will produce support requests for sure - which I rather avoid if there is no need.
