### ISSUE TITLE
Listen only on interface eth0 setting do not work

### ISSUE THREAD

**Issue by kolargol** [pi-hole/web#2009]
### Versions
  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is v5.10.2 (Latest: v5.10.2)

### Platform
- Platform:  Debian 10.10

### Expected behavior

Setting "Listen only on interface eth0" should listen on eth0 interface

### Actual behavior / bug

DNS listen on all interfaces in the system

### Steps to reproduce

Set "Listen only on interface eth0" in admin/settings (web interface), check on system:

netstat -plan | grep 53
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      13284/pihole-FTL    
tcp6       0      0 :::53                   :::*                    LISTEN      13284/pihole-FTL    
udp        0      0 0.0.0.0:53              0.0.0.0:*                           13284/pihole-FTL    
udp6       0      0 :::53                   :::*                                13284/pihole-FTL

**Comment by Asleep-at-the-wheel** [comment]
Ok, this makes sense.

The web interface should probably refer to it as "**respond from**" rather than "**listen**" if that's the case.

It should also be made clear that PiHole is incompatible with libvirt too. Libvirt default is a virtual network adapter running NAT and dnsmasq as seen in my above post. If binding to * is not going to change then those two applications can't be run on the same machine.

**Comment by DL6ER** [comment]
Not being a native speaker, I'm always thankful for such suggestions. I will also add a reference to our documentation: https://docs.pi-hole.net/ftldns/interfaces/#technical-details

**Comment by kolargol** [comment]
Ok so this option should be renamed as it is nowhere close to "Listen on" which is "industry standard" meaning one thing and not anything else: process binds to specified interface and that's it.

Btw, I think it would be nice to have option to bind to specified interface despite possibility it will go off and on. In systems where there are multiple interfaces and services that would be helpful. Now it need to fiddle with listen ports on them which make everything more complex and confusing :)

**Comment by DL6ER** [comment]
I was thinking about something like this

![Screenshot from 2021-12-19 10-01-43](https://user-images.githubusercontent.com/16748619/146669400-a29fbc90-ae77-4398-8459-5265676f6a12.png)

**Comment by Asleep-at-the-wheel** [comment]
That is still confusing to me, because the option Bind only to interface enp2s0 makes it sound like the issue we had earlier.

If you are binding wild card then perhaps the term **binding** should be done away with all together, because it becomes more of an access list or filtering system rather than a binding system.

Options like:
- Allow from only local network
- Respond only on X
- Permit all

Make more sense to me, but that's because I am a networking simpleton and not a developer I guess. I am not a developer so I appreciate everything anyways.

**Comment by DL6ER** [comment]
> That is still confusing to me, because the option Bind only to interface enp2s0 makes it sound like the issue we had earlier.

Yes, this is an altogether fourth, new option that implements exactly what were talking about here: `interface=eth0` in combination with `bind-interfaces`.

The other options avoid the terms "bind" and "listen".

**Comment by Asleep-at-the-wheel** [comment]
Oh!

In that case it makes perfect sense!

Great work.

**Comment by yubiuser** [comment]
This should be fixed with
https://discourse.pi-hole.net/t/pi-hole-ftl-v5-12-web-v5-9-and-core-v5-7-released/51795/1
