### ISSUE TITLE
The number of domains in the blacklist is not displayed on the pi-hole panel

### ISSUE THREAD

**Issue by DHYTFG** [pi-hole/web#2395]
### Versions

- Pi-hole:  v5.13
- AdminLTE:  v5.16
- FTL:  v5.18.2

### Platform

- OS and version:  Debian 11

- Platform:  VPS

### Expected behavior

When I log in to the pi-hole admin panel, I see the number of domains in the blacklist.

### Actual behavior / bug

When logging into the pi-hole admin panel, I don't see the number of domains in the blacklist. The value "0" is shown.

### Steps to reproduce

1. Go to 'pi-hole admin panel'
2. See error

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
