### ISSUE TITLE
Problems with PiOLED and PiTFT since the last update

### ISSUE THREAD

**Issue by Falconcrest** [pi-hole/web#2467]
Hello,

since the last update, the displays of 2 Pi-hole with PiOLED and PiTFT are black.
Pi-hole data is no longer displayed.
I set up both displays a while ago following the instructions below:

[https://learn.adafruit.com/pi-hole-ad-blocker-with-pi-zero-w/install-pioled](url)
[https://learn.adafruit.com/pi-hole-ad-blocker-with-pi-zero-w/install-mini-pitft](url)

If I run the command sudo python3 stats.py once on the Pi-hole with PiTFT I get the following output:

root@pihole-backup-I:/home/dietpi# sudo python3 stats.py
Traceback (most recent call last):
File "stats.py", line 109, in <module>
DNSQUERIES = data['dns_queries_today']
TypeError: list indices must be integers or slices, not str

and on the Pi-Hole with PiOLED I get the following output:

root@pihole-backup-II:~# sudo python3 stats.py
Traceback (most recent call last):
File "/root/stats.py", line 96, in <module>
DNSQUERIES = data['dns_queries_today']
TypeError: list indices must be integers or slices, not str

Excerpts from both relevant lines of the respective stats.py:

PiTFT stats.py

    # Pi Hole data!
    try:
        r = requests.get(api_url)
        data = json.loads(r.text)
        DNSQUERIES = data['dns_queries_today'] **#line 109 !**
        ADSBLOCKED = data['ads_blocked_today']
        CLIENTS = data['unique_clients']
    except KeyError:
        time.sleep(1)
        continue

PiOLED stats.py

    # Pi Hole data!
    try:
        r = requests.get(api_url)
        data = json.loads(r.text)
        DNSQUERIES = data['dns_queries_today'] **#line109 !**
        ADSBLOCKED = data['ads_blocked_today']
        CLIENTS = data['unique_clients']
    except KeyError:
        time.sleep(1)
        continue

Can the error be due to the changes in Pi-hole FTL?

**Comment by DL6ER** [comment]
This is caused by https://github.com/pi-hole/AdminLTE/pull/2411 see also our announcement in November about this upcoming change: https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/

There you can also find a description how to fix your scripts.

**Comment by Falconcrest** [comment]
Thank you for the info.

Since another Pi-hole with TFT and PADD does not show any problems in this regard, I can assume that the necessary adjustments have already been made to padd.sh?

**Comment by yubiuser** [comment]
PADD does not query the web API, but directly FTL's telnet API.

**Comment by Falconcrest** [comment]
Ok, Thanks.

Since I don't feel able to make these adjustments in the Python script due to a lack of programming knowledge, I have to see if I can find help.

**Comment by DL6ER** [comment]
The python scripts you are using has `requests.get(api_url)` - where does this `api_url` come from?

As mentioned in the blog post, if there is a line like

``` python
api_url = "http://pi.hole/admin/api.php?status"
```

somewhere, you will only have to change this to

``` python
api_url = "http://pi.hole/admin/api.php?status&auth=abcdef123456789"
```
where you can get the actual token (`abcdef123456789` is just a placeholder above) from the Pi-hole web interface (see Settings -> API -> Show API token) or by running `grep WEBPASSWORD /etc/pihole/setupVars.conf` on your Pi-hole.

**Comment by Falconcrest** [comment]
It doesn't seem to be that difficult normally, but...

Here are a few lines that might apply:


-# Import Python Imaging Library
from PIL import Image, ImageDraw, ImageFont

api_url = 'http://localhost/admin/api.php'


If I replace this line with

api_url = 'http://localhost/admin/api.php?status&auth=abcdef123456789'

then unfortunately it still doesn't work.
Of course I replaced <abcdef123456789> with my token, also the <"> with <'>, because that's how it is in the original script.

**Comment by yubiuser** [comment]
Can you access the data if you open the URL in your bowser (if you are not logged-in the web dashboard)?

**Comment by Falconcrest** [comment]
Yes, data is displayed. For output I used the browser on my PC.
When I enter http://10.0.0.XXX/admin/api.php with the password disabled, it shows:

JSON
domains_being_blocked: 12345
dns_queries_today: 38
.
.
.
status: "enabled"

If I enter http://10.0.0.XXX/admin/api.php?status&auth=abcdef123456789 with an active password then only appears

JSON
status: "enabled"

**Comment by DL6ER** [comment]
Sorry, the confusion comes from that you called `api.php` before and explicitly ask for `?status` now. However, the `status` call does not include what you want so you should actually either be using

``` python
api_url = 'http://localhost/admin/api.php?auth=abcdef123456789'
```
(as before with added `auth=...`)

or

``` python
api_url = 'http://localhost/admin/api.php?summary&auth=abcdef123456789'
```
(being fully explicit).

Both should return identical information.

**Comment by Falconcrest** [comment]
api_url = 'http://localhost/admin/api.php?summary&auth=abcdef123456789'

was the solution! That's how it works.
I thank you for the great support.

**Comment by Falconcrest** [comment]
I now have the same problem with accessing the api_url with an RPi Zero W and an e-Paper Display.
Well, I've already learned a lot about it from this post here, but the solution, once again, isn't that easy for me.

The e-paper is addressed using the pihole-dashboard.
https://github.com/santoru/pihole-dashboard

I temporarily disabled the password and it works so far, it is of course better with an activated password.
I think, I found the corresponding line in the __init__.py file, but I haven't been able to create the correct entry so far.

`def update():
    url = "http://127.0.0.1:{}/admin/api.php".format(PIHOLE_PORT)
    r = json.load(urllib.request.urlopen(url))`

Both of the variants shown here do not work that way.

I also contacted the developer at
https://github.com/santoru/pihole-dashboard/issues/9

**Comment by DL6ER** [comment]
It should be something like
``` python
def update():
    url = "http://127.0.0.1:{}/admin/api.php?summaryRaw&auth=abcdef123456789".format(PIHOLE_PORT)
    r = json.load(urllib.request.urlopen(url))
```
but this isn't the best way of doing this (the password hash should be a variable as well).

**Comment by rdwebdesign** [comment]
I think this should work (untested - I usually don't work with Python):

- around line 35, add `PIHOLE_APITOKEN`:
  ```py
  PIHOLE_PORT = 80
  PIHOLE_APITOKEN = "abcdef123456789"
  ```


- Inside the `update()` function, add `?summaryRaw&auth={}` to the URL and add `PIHOLE_APITOKEN` to `.format()` 
  ```py
  def update():
      url = "http://127.0.0.1:{}/admin/api.php?summaryRaw&auth={}".format(PIHOLE_PORT, PIHOLE_APITOKEN)
      r = json.load(urllib.request.urlopen(url))
  ```

**Comment by madryboy** [comment]
Hello I am very new here but I have also ran into the issue where the e-ink screen is not displaying I attempted to follow along and change the stats.py script file and updated it with the proper api key but now I seem to get another issue or possibly I was supposed to modify another file also but here is the output after running the scripts file after adding the api key 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xb5a192f8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='pi.hole', port=80): Max retries exceeded with url: /admin/api.php?summary&auth=03df10c414f9f496db6e4063e9fcb2a210edd6c4c64b93305b6f30e1457d71f5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5a192f8>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/python/stats.py", line 54, in <module>
    r = requests.get(api_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='pi.hole', port=80): Max retries exceeded with url: /admin/api.php?summary&auth=03df10c414f9f496db6e4063e9fcb2a210edd6c4c64b93305b6f30e1457d71f5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5a192f8>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by madryboy** [comment]
Hello I also updated and was unable to view anything on the e-ink screen so I went through and attempted to follow the changed made by the posts above by adding the necessary token keys into the stats script but now for some reason I get this error 
Traceback (most recent call last):
  File "/home/pi/python/stats.py", line 67, in <module>
    draw.text((x, top), "HOST: " + HOST, font=font, fill=fill_color)
TypeError: can only concatenate str (not "bytes") to str

update: a friend of mine said that changing line 67
from  
` draw.text((x, top), "HOST: " + HOST, font=font, fill=fill_color)`
to
 ` draw.text((x, top), "HOST: " + str(HOST), font=font, fill=fill_color)`
but I noticed when I ran the script it appeared to work but there appears to be random /B and N characters so im not to sure this is the most efficient or correct way of doing this 

any help is much appreciated also if I am posting in the wrong section my apologies I just found this as the most relevant

**Comment by rdwebdesign** [comment]
Your error is happening on a third party app, not developed by Pi-hole.

If none of the above suggestions work for you, please ask your question to the app developers.

**Comment by Falconcrest** [comment]
@DL6ER , @rdwebdesign 

Sorry I haven't responded to your tips yet, but this pi-hole isn't on site. But I think I'll test it this week.

**Comment by Falconcrest** [comment]
> I think this should work (untested - I usually don't work with Python):
> 
>     * around line 35, add `PIHOLE_APITOKEN`:
>       ```python
>       PIHOLE_PORT = 80
>       PIHOLE_APITOKEN = "abcdef123456789"
>       ```
> 
>     * Inside the `update()` function, add `?summaryRaw&auth={}` to the URL and add `PIHOLE_APITOKEN` to `.format()`
>       ```python
>       def update():
>           url = "http://127.0.0.1:{}/admin/api.php?summaryRaw&auth={}".format(PIHOLE_PORT, PIHOLE_APITOKEN)
>           r = json.load(urllib.request.urlopen(url))
>       ```

I have now entered everything as described,
unfortunately I get the following error message:

```
pi@alpenblick:~/pihole-dashboard/pihole_dashboard $ python3 __init__.py
   File "/home/pi/pihole-dashboard/pihole_dashboard/__init__.py", line 86
     try:
         ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by rdwebdesign** [comment]
As I said, this was not tested.

Also note: this is an external app. 
Please, ask for help here: https://github.com/santoru/pihole-dashboard
