### ISSUE TITLE
without /admin at the end of the URL the web interface doesn't work

### ISSUE THREAD

**Issue by KevanGP** [pi-hole/web#2778]
### Versions

   Pi-hole version is v5.17.1 (Latest: v5.17.2)                                  
   AdminLTE version is v5.20.1 (Latest: null)                                    
   FTL version is v5.23 (Latest: v5.23)                                          

### Platform

- OS and version:     Operating System: Debian GNU/Linux 11 (bullseye)                            

- Platform:  Raspberry Pi

### Expected behavior
When I visit "192.168.x.xx/" in a browser, the web controls should work.

### Actual behavior / bug

The page displays a placeholder from the web server package you use, Lighttpd.

### Steps to reproduce

Visit the address of the device in a web browser, without anything at the end except a slash.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I fixed the problem by adding index.html to the web directory /var/html, The file contains HTML code for a simple redirect to /admin/.

**Comment by rdwebdesign** [comment]
This was announced in our [Discourse Forum](https://discourse.pi-hole.net/t/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/60495?u=rdwebdesign):
> Automatic redirection to `/admin` will only happen if you browse via `http://pi.hole`. If you wish to browse via `http://[IP Address]`, then you will need to ensure that you add `/admin` manually.

This is by design.
Some users already have `lighttpd` serving pages on the root. 

The new config was created to avoid overwriting user's previous config and to allow the use of custom pages (like you did) on the root.
