### ISSUE TITLE
Division by 0 in header_authenticated.php

### ISSUE THREAD

**Issue by enginelesscc** [pi-hole/web#3154]
### Info

I initially wanted to open a PR but the guidelines got me a bit unsure given this affects v5 only while v6 is lua now and doesnt have the affected code..

But I found it may still be useful to post for anyone currently affected until v6 is released.

The simple fix for this is here:

[pi-hole/web/commit/bbcf9fa857002010d3c61c04f90a35ec6c31cea2](https://github.com/pi-hole/web/commit/bbcf9fa857002010d3c61c04f90a35ec6c31cea2)

### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.21
- FTL:  v5.25.2

### Platform

- OS and version:  Debian Sid

- Platform:  LXD/Incus container

### Expected behavior

Functional Webinterface / data validation

### Actual behavior / bug

`/proc/meminfo` may return no data in a linux container (in my case: incus), causing the `$data` array to be incomplete.
This resulted in a `division by 0` error trying to divide by non-existant `$meminfo['MemTotal']`.
This meant pihole-web was unusable (error 500).

### Steps to reproduce

n/A

## Debug Token

n/A

### Screenshots

n/A

### Additional context

n/A

**Comment by rdwebdesign** [comment]
Thank you for the information.

Reading the code, it's obvious that a "Division by 0" will happen if `$meminfo['MemTotal']` is zero (nice catch), but to be honest, you are probably the only user facing this issue, because we've never received similar complaints.

It is very unlikely that there will be another v5 release. As you noticed, the current code in development branch is for Pi-hole v6. 

I will keep this issue open until we release v6, so other users can use your fix, if needed.

--- 

Why did you change line 44?
This is not needed to fix the issue and I don't think it will be possible to have less than 4 lines if `/proc/meminfo` exists.

**Comment by enginelesscc** [comment]
> Why did you change line 44?

Because an empty /proc/meminfo results in an `array(1) { [0] = "" }`.

Meaning the previous > 0 check was always evaluating to `true`.

Therefore I made the assumption more specific to contain at-least as many elements as accessed. (So we hit our else branch here setting -1)

The max() is an additional case to avoid err 500 if /proc/meminfo returns bogus data.

Both changes seemed valid to me^
